version: "3.5"
services:
  front-dev:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - "metrics-service"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 1
      DISABLE_ESLINT_PLUGIN: 1

  metrics-service:
    container_name: metrics-service
    build:
      context: ./metrics-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./metrics-service:/app
      - /app/node_modules
    restart: always
